# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS example workflow
on:
  push
env:
  AWS_REGION : "us-east-2"
# permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
   AwsEC2list:  
    runs-on: ['self-hosted']
    steps:
      # - name: Git clone the repository
      - uses: actions/checkout@v3 
      # - uses: quipper/setup-aws-cli-action@main  
      - name: Install AWS CLI v2
        run:  |
              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip
              unzip -q /tmp/awscliv2.zip -d /tmp
              rm /tmp/awscliv2.zip
              sudo /tmp/aws/install --update
              rm -rf /tmp/aws/ 
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::564087180491:role/github-ci20230117183754324600000001
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name:  list ec2
        run: |
          - aws version
          # - aws ec2 describe-instances --region us-east-2
          # - aws s3 ls

